component: http
name: http-koa-089kpZqqv
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    framework: koa
    name: '${name}'
    runtime: Nodejs12.16
    eip: false
    timeout: 3
    memorySize: 512
    tags: []
    environments: []
    layers:
      - name: '${output:${stage}:${app}:byte-koa-layer.name}'
        version: '${output:${stage}:${app}:byte-koa-layer.version}'
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  region: ap-guangzhou
  isAutoCiDeploy: false
org: '1259409954'
app: byte-koa
stage: dev
